server:
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#解决首次访问可能失败问题，1秒
hystrix:
  command:
    default:
      execution:
        timeout: 
          enabled: false #禁用超时
          
zuul:
  prefix: /v1
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
        
spring:

  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址

  cloud:
    stream:
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.52.130
                port: 5672
                username: guest
                password: guest
                virtual-host: /
                
    bus:
      trace:
        enabled: true
      enabled: true